[package]
name = "rust_interop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc="*"

[lib]
path="src/lib.rs"
crate-type=["staticlib"]
